debug: true

web:
  host: "127.0.0.1"
  port: 8000

admin:
  email: "admin@100k1.com"
  password: "change-me"  # ADMIN_PASSWORD

sentry:
  dsn: ""
  env: "dev"

store: {}

database:
  host: "localhost"
  port: 5432
  user: "game_user"
  password: "game_password"
  database: "hundred_to_one"

session:
  key: "GA3tS842NyGonGJYYc31CKILfHMSIuIXZO1bHbtIDHc="  # dev-only, override with SESSION_KEY

telegram:
  token: ""  # TELEGRAM_TOKEN
  polling_interval: 1