"""add_current_timer_id_to_game_sessions

Revision ID: a69b31b14636
Revises: cdf01d45e7dd
Create Date: 2025-10-08 23:35:44.360620

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a69b31b14636"
down_revision: str | None = "cdf01d45e7dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("game_states")
    op.drop_table("admins")
    op.drop_table("scheduled_events")
    op.drop_table("web_admins")
    op.alter_column(
        "answer_variants",
        "text",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.add_column(
        "game_sessions",
        sa.Column("current_timer_id", sa.String(length=20), nullable=True),
    )
    op.alter_column(
        "game_sessions",
        "state",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Text(),
        nullable=False,
    )
    op.alter_column(
        "game_sessions",
        "total_questions",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "game_sessions",
        "current_question_number",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "game_sessions",
        "current_question_round",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "game_sessions",
        "max_rounds_per_question",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("3"),
    )
    op.alter_column(
        "game_sessions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "game_sessions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.drop_column("game_sessions", "revealed_variants")
    op.alter_column(
        "player_answers",
        "player_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "player_answers", "round", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "player_answers",
        "answer_text",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "player_answers",
        "normalized_text",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "player_answers",
        "points_earned",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "player_answers",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "players",
        "username",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "players", "rating", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "players", "games_played", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "players", "wins", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "players",
        "total_points",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "players",
        "date_created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "questions",
        "text",
        existing_type=sa.VARCHAR(length=70),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "questions", "is_active", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "session_players",
        "player_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "session_players",
        "is_admin",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "session_players",
        "final_score",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "session_players",
        "joined_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "session_players",
        "joined_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "session_players",
        "final_score",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "session_players", "is_admin", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "session_players",
        "player_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "questions", "is_active", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "questions",
        "text",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=70),
        existing_nullable=False,
    )
    op.alter_column(
        "players",
        "date_created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "players",
        "total_points",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "players", "wins", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "players", "games_played", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "players", "rating", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "players",
        "username",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=30),
        existing_nullable=True,
    )
    op.alter_column(
        "player_answers",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "player_answers",
        "points_earned",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "player_answers",
        "normalized_text",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "player_answers",
        "answer_text",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "player_answers", "round", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "player_answers",
        "player_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.add_column(
        "game_sessions",
        sa.Column(
            "revealed_variants",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "game_sessions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "game_sessions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "game_sessions",
        "max_rounds_per_question",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("3"),
    )
    op.alter_column(
        "game_sessions",
        "current_question_round",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "game_sessions",
        "current_question_number",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "game_sessions",
        "total_questions",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "game_sessions",
        "state",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=20),
        nullable=True,
    )
    op.drop_column("game_sessions", "current_timer_id")
    op.alter_column(
        "answer_variants",
        "text",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.create_table(
        "web_admins",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "email", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "password_hash",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "permissions",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="web_admins_pkey"),
        sa.UniqueConstraint("email", name="web_admins_email_key"),
    )
    op.create_table(
        "scheduled_events",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "session_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "event_type",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "execute_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "event_data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_completed", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["game_sessions.id"],
            name="scheduled_events_session_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="scheduled_events_pkey"),
    )
    op.create_table(
        "admins",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "player_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "session_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "is_super_admin", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name="admins_player_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["game_sessions.id"], name="admins_session_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="admins_pkey"),
    )
    op.create_table(
        "game_states",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "session_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "state_data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["game_sessions.id"],
            name="game_states_session_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="game_states_pkey"),
    )
    # ### end Alembic commands ###